In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#data=pd.read_csv('Salary_dataset.csv')

In [2]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [3]:
#X_train=data.drop('price',axis='columns').to_numpy()
#y_train=data['price'].to_numpy()
print(X_train)
print(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [4]:
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [5]:
def compute_cost_multi_variable(X, y, w, b):
    m = X.shape[0]
    total_cost = 0
    for i in range(m):
        f_wb = np.dot(X[i], w) + b
        total_cost += (f_wb - y[i]) ** 2
    total_cost = total_cost / (2 * m)
    return total_cost

In [ ]:
def gradient_calculation(X, y, w, b):
    m,n= X.shape
    dj_dw = np.zeros(n)
    dj_db = 0
    for i in range(m):
        f_wb = np.dot(X[i], w) + b
        error = f_wb - y[i]
        for j in range(n):
            dj_dw[j] += error * X[i][j]
        dj_db += error
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    return dj_dw, dj_db


In [7]:
def gradient_descent_multi_variable(X, y, w_in, b_in, alpha, num_iters, gradient_calculation, compute_cost_multi_variable):
    J_history = []
    w = w_in
    b = b_in
    for i in range(num_iters):
        dj_dw, dj_db = gradient_calculation(X, y, w, b) 
        w = w - alpha * dj_dw
        b = b - alpha * dj_db
        if i<100000:       
            J_history.append(compute_cost_multi_variable(X, y, w, b))
        
        if i%10== 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")
    return w, b, J_history

In [8]:
w_init = np.zeros(X_train.shape[1])
b_init = 0
iterations = 1000
learning_rate = 5e-7
w_final, b_final, J_history = gradient_descent_multi_variable(X_train, y_train, w_init, b_init, learning_rate, iterations, gradient_calculation, compute_cost_multi_variable)
print(f"Final weights:", w_final)
print(f"Final bias:", b_final)

Iteration    0: Cost  2529.46   
Iteration   10: Cost   696.96   
Iteration   20: Cost   696.85   
Iteration   30: Cost   696.74   
Iteration   40: Cost   696.64   
Iteration   50: Cost   696.53   
Iteration   60: Cost   696.42   
Iteration   70: Cost   696.31   
Iteration   80: Cost   696.21   
Iteration   90: Cost   696.10   
Iteration  100: Cost   695.99   
Iteration  110: Cost   695.88   
Iteration  120: Cost   695.78   
Iteration  130: Cost   695.67   
Iteration  140: Cost   695.56   
Iteration  150: Cost   695.45   
Iteration  160: Cost   695.35   
Iteration  170: Cost   695.24   
Iteration  180: Cost   695.13   
Iteration  190: Cost   695.03   
Iteration  200: Cost   694.92   
Iteration  210: Cost   694.81   
Iteration  220: Cost   694.71   
Iteration  230: Cost   694.60   
Iteration  240: Cost   694.50   
Iteration  250: Cost   694.39   
Iteration  260: Cost   694.28   
Iteration  270: Cost   694.18   
Iteration  280: Cost   694.07   
Iteration  290: Cost   693.97   
Iteration 